# Generated by Django 5.1.3 on 2024-11-14 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_product_alter_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('datetime', models.DateTimeField()),
                ('department', models.CharField(max_length=20)),
                ('doctor', models.CharField(max_length=20)),
                ('message', models.TextField()),
            ],
        ),
    ]
